language: node_js

node_js:
  - '8'
  
cache: yarn

install:
  - yarn install

before_script: cd package

script: npm install codecov -g

deploy:
  provider: npm
  email: '$NPM_EMAIL'
  api_key: '$NPM_TOKEN'
  skip_cleanup: true
  on:
    tags: true
    all_branches: true

after_success:
  - codecov