language: node_js

node_js:
  - '13.6.0'
  
cache: yarn

script:
  - npm install codecov -g
  - cd implementation
  - yarn
  - yarn test
  - codecov
  - cd ../package
  - yarn

deploy:
  provider: npm
  email: '$NPM_EMAIL'
  api_key: '$NPM_TOKEN'
  skip_cleanup: true
  on:
    tags: true
    all_branches: true